<?php

namespace ContainerCtqHfep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H0TJUIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H0TJU_i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H0TJU_i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
        ], [
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
        ]);
    }
}
