<?php

namespace ContainerCtqHfep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QgzYISService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qgzY_iS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qgzY_iS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aboutRepository' => ['privates', 'App\\Repository\\AboutRepository', 'getAboutRepositoryService', true],
        ], [
            'aboutRepository' => 'App\\Repository\\AboutRepository',
        ]);
    }
}
