<?php

namespace ContainerCtqHfep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ll_R1J0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ll.r1J0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ll.r1J0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'homepageRepository' => ['privates', 'App\\Repository\\HomepageRepository', 'getHomepageRepositoryService', true],
        ], [
            'homepageRepository' => 'App\\Repository\\HomepageRepository',
        ]);
    }
}
