<?php

namespace ContainerCtqHfep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TfaOhNPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TfaOhNP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TfaOhNP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'about' => ['privates', '.errored..service_locator.TfaOhNP.App\\Entity\\About', NULL, 'Cannot autowire service ".service_locator.TfaOhNP": it references class "App\\Entity\\About" but no such service exists.'],
        ], [
            'about' => 'App\\Entity\\About',
        ]);
    }
}
