<?php

namespace ContainerCtqHfep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TfaOhNP.App\Entity\About' shared service.
     *
     * @return \App\Entity\About
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TfaOhNP": it references class "App\\Entity\\About" but no such service exists.');
    }
}
