<?php

namespace ContainerCtqHfep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SecP8IS.App\Entity\Services' shared service.
     *
     * @return \App\Entity\Services
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SecP8IS": it references class "App\\Entity\\Services" but no such service exists.');
    }
}
