<?php

namespace ContainerCMLWcxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SecP8ISService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SecP8IS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SecP8IS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'service' => ['privates', '.errored..service_locator.SecP8IS.App\\Entity\\Services', NULL, 'Cannot autowire service ".service_locator.SecP8IS": it references class "App\\Entity\\Services" but no such service exists.'],
        ], [
            'service' => 'App\\Entity\\Services',
        ]);
    }
}
